# Default experiment configuration
seed: 42
k_clusters: 5

model:
  hidden_dim: 64
  latent_dim: 16
  n_layers: 1

training:
  epochs: 30
  batch_size: 128
  learning_rate: 1e-3

umap:
  n_neighbors: 15
  min_dist: 0.1

paths:
  data_dir: data
  output_dir: outputs
  results_dir: results
  master_csv: data/master_sheet.csv

